# SPDX-FileCopyrightText: 2024-2025 Idiap Research Institute <contact@idiap.ch>
# SPDX-FileContributor: Olivier Canévet <olivier.canevet@idiap.ch>
# SPDX-License-Identifier: MIT

stages:
  - build
  - qa
  - test
  - deploy


.images:
  parallel:
    matrix:
      - PYTHON_MAJOR: ["3"]
        PYTHON_MINOR: ["9", "10", "11"]
  variables:
    OUTPUT_DIR: $PYTHON_MAJOR-$PYTHON_MINOR
    IMAGE_NAME: $CI_REGISTRY_IMAGE:$PYTHON_MAJOR-$PYTHON_MINOR
  before_script:
    - mkdir -p $OUTPUT_DIR


build_image:
  extends: .images
  stage: build
  image:
    name: docker
  tags:
    - linux
    - docker
  script:
    - echo "machine gitlab.idiap.ch" > .netrc
    - echo "login biped" >> .netrc
    - echo "password $BIPED_REPO" >> .netrc
    - docker build --build-arg PYTHON_MAJOR=$PYTHON_MAJOR --build-arg PYTHON_MINOR=$PYTHON_MINOR --tag $IMAGE_NAME .
    - echo "$CI_REGISTRY_PASSWORD" | docker login -u "$CI_REGISTRY_USER" --password-stdin "$CI_REGISTRY"
    - docker push $IMAGE_NAME
  rules:
    - changes:
      - Dockerfile
      - pyproject.toml
      - requirements.txt


reuse:
  stage: qa
  image:
    name: fsfe/reuse:latest
    entrypoint: [""]
  tags:
    - linux
    - docker
  script:
    - reuse lint


python_version:
  extends: .images
  stage: test
  image:
    name: $IMAGE_NAME
  tags:
    - linux
    - docker
  script:
    - python3 --version


irt_version:
  extends: .images
  stage: test
  image:
    name: $IMAGE_NAME
  tags:
    - linux
    - docker
  script:
    - pip uninstall irt
    - pip install -e .
    - python3 -c "import irt ; print(irt.__version__)"


test_utils:
  extends: .images
  stage: test
  image:
    name: $IMAGE_NAME
  tags:
    - linux
    - docker
  script:
    - pip uninstall irt
    - pip install -e .
    - python3 -m unittest tests/test_utils.py -v


test_robot:
  extends: .images
  stage: test
  image:
    name: $IMAGE_NAME
  tags:
    - linux
    - docker
  script:
    - pip uninstall irt
    - pip install -e .
    - python3 -m unittest tests/test_robot.py -v


test_fake:
  extends: .images
  stage: test
  image:
    name: $IMAGE_NAME
  tags:
    - linux
    - docker
  script:
    - pip uninstall irt
    - pip install -e .
    - python3 -m unittest tests/test_fake.py -v


deploy:
  stage: deploy
  image:
    name: squidfunk/mkdocs-material:latest
    entrypoint: ["/bin/sh", "-c"]
  tags:
    - linux
    - docker
  script:
    - mkdocs build --site-dir public
  pages: true
  artifacts:
    paths:
      - public
