stages:
  - build
  - test

build_image:
  stage: build
  image:
    name: docker
  tags:
    - linux
    - docker
  script:
    - docker build --tag $CI_REGISTRY_IMAGE .
    - echo "$CI_REGISTRY_PASSWORD" | docker login -u "$CI_REGISTRY_USER" --password-stdin "$CI_REGISTRY"
    - docker push $CI_REGISTRY_IMAGE
  rules:
    - changes:
      - Dockerfile
      - requirements.txt

python_version:
  stage: test
  image:
    name: $CI_REGISTRY_IMAGE
  tags:
    - linux
    - docker
  script:
    - python3 --version

irt_version:
  stage: test
  image:
    name: $CI_REGISTRY_IMAGE
  tags:
    - linux
    - docker
  script:
    - pip uninstall irt
    - pip install -e .
    - python3 -c "import irt ; print(irt.__version__)"

test_robot:
  stage: test
  image:
    name: $CI_REGISTRY_IMAGE
  tags:
    - linux
    - docker
  script:
    - pip uninstall irt
    - pip install -e .
    - python3 -m unittest tests/test_utils.py -v

test_robot:
  stage: test
  image:
    name: $CI_REGISTRY_IMAGE
  tags:
    - linux
    - docker
  script:
    - pip uninstall irt
    - pip install -e .
    - python3 tests/test_robot.py

test_fake:
  stage: test
  image:
    name: $CI_REGISTRY_IMAGE
  tags:
    - linux
    - docker
  script:
    - pip uninstall irt
    - pip install -e .
    - python3 tests/test_fake.py
