site_name: The Idiap Robot Toolkit
site_url: https://idiap.github.io/idiap_robot_toolkit/
repo_url: https://github.com/idiap/idiap_robot_toolkit
copyright: Copyright 2025 Idiap Research Institute

use_directory_urls: false

theme:
  name: material
  language: en
  custom_dir: overrides
  features:
    - navigation.top
    - navigation.indexes
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.instant.progress
  font:
    text: Open Sans
  icon:
    logo:
      fontawesome/solid/robot # idiap/logo-white
  favicon:
    assets/images/favicon.ico
  palette:
    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: blue
      accent: blue
      toggle:
        icon: material/weather-night
        name: Switch to dark mode
    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: black
      accent: blue
      toggle:
        icon: material/weather-sunny
        name: Switch to light mode

nav:
  - "Home": README.md
  - "Wizard-of-Oz": wizard-of-oz.md
  - "Pepper": pepper.md

markdown_extensions:
  - abbr
  - admonition
  - attr_list
  - def_list
  - footnotes
  - md_in_html
  - toc:
      toc_depth: 2
      permalink: true
  # Python Markdown Extensions
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.details
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
      options:
        custom_icons:
          - overrides/.icons
  - pymdownx.highlight
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.arithmatex:
      generic: true

extra:
  generator: true
  social:
    - icon: fontawesome/solid/phone
      link: tel:0041277217711
    - icon: fontawesome/regular/envelope
      link: https://www.idiap.ch/en/idiap-contact-form
    - icon: fontawesome/brands/youtube
      link: https://www.youtube.com/@IdiapCh/videos
    - icon: fontawesome/brands/x-twitter
      link: https://x.com/Idiap_ch


extra_css:
  - stylesheets/extra.css

extra_javascript:
  - javascripts/mathjax.js
  - https://unpkg.com/mathjax@3/es5/tex-mml-chtml.js
