# SPDX-FileCopyrightText: 2024-2026 Idiap Research Institute <contact@idiap.ch>
# SPDX-FileContributor: Olivier Canévet <olivier.canevet@idiap.ch>
# SPDX-License-Identifier: MIT

[build-system]
requires = ["setuptools>=61.0", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "idiap_robot_toolkit"
version = "0.6.3"
description = "Idiap's Robot Toolkit"
authors = [
  {name = "Olivier Canévet", email = "olivier.canevet@idiap.ch"},
]
license = "MIT"
readme = "README.md"

classifiers = [
  "Development Status :: 4 - Beta",
  "License :: OSI Approved :: MIT License",
  "Programming Language :: Python",
  "Programming Language :: Python :: 3 :: Only",
  "Programming Language :: Python :: 3.7",
  "Programming Language :: Python :: 3.8",
  "Programming Language :: Python :: 3.9",
  "Programming Language :: Python :: 3.10",
  "Programming Language :: Python :: 3.11",
  "Operating System :: Unix",
]

requires-python = ">=3.7"

dynamic = ["dependencies"]

[project.urls]
Documentation = "https://idiap.github.io/idiap-robot-toolkit"
Repository = "https://github.com/idiap/idiap-robot-toolkit"

[project.scripts]
qi_robot_wizard = "idiap_robot_toolkit.scripts.qi_robot_wizard:main"
run_robot_func = "idiap_robot_toolkit.scripts.run_robot_func:main"

[tool.setuptools]
packages = [
  "idiap_robot_toolkit",
  "idiap_robot_toolkit.scripts",
]

[tool.setuptools.package-data]
idiap_robot_toolkit = [
  "configs/*.yaml",
  "resources/empty.html",
]

[tool.setuptools.dynamic]
dependencies = { file = ["requirements.txt"] }
