# SPDX-FileCopyrightText: Copyright 2024-2025 Idiap Research Institute <contact@idiap.ch>
# SPDX-FileContributor: Olivier Canévet <olivier.canevet@idiap.ch>
# SPDX-License-Identifier: See LICENSE
#
# This file is part of the irt package

[build-system]
requires = ["setuptools>=61.0", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "irt"
version = "0.5.0"
description = "Idiap's Robot Toolkit"
authors = [
  {name = "Olivier Canévet", email = "olivier.canevet@idiap.ch"},
]
license-files = ["LICENSE"]
readme = "README.md"

classifiers = [
  "Development Status :: 4 - Beta",
  "Programming Language :: Python",
  "Programming Language :: Python :: 3 :: Only",
  "Programming Language :: Python :: 3.8",
  "Programming Language :: Python :: 3.9",
  "Programming Language :: Python :: 3.10",
  "Programming Language :: Python :: 3.11",
  "Programming Language :: Python :: 3.12",
  "Operating System :: Unix",
]

requires-python = ">=3.7"

dynamic = ["dependencies"]

[project.scripts]
qi_robot_wizard = "irt.scripts.qi_robot_wizard:main"
run_robot_func = "irt.scripts.run_robot_func:main"

[tool.setuptools]
packages = ["irt"]

[tool.setuptools.dynamic]
dependencies = { file = ["requirements.txt"] }
