[build-system]
requires = ["setuptools>=61.0", "wheel"]
build-backend = "setuptools.build_meta"


[project]
name = "irt"
version = "0.3.0"
description = "Idiap's Robot Toolkit"
authors = [
  {name = "Olivier Canévet", email = "olivier.canevet@idiap.ch"},
]
license = { file = "LICENSE" }
readme = "README.md"

classifiers = [
  "Development Status :: 4 - Beta",
  "Programming Language :: Python",
  "Programming Language :: Python :: 3",
  "Operating System :: Unix",
]

requires-python = ">=3.7"

dynamic = ["dependencies"]

[project.scripts]
qi_robot_wizard = "irt.scripts.qi_robot_wizard:main"

[tool.setuptools]
py-modules = []

[tool.setuptools.dynamic]
dependencies = { file = ["requirements.txt"] }
