# SPDX-FileCopyrightText: 2024-2026 Idiap Research Institute <contact@idiap.ch>
# SPDX-FileContributor: Olivier Canévet <olivier.canevet@idiap.ch>
# SPDX-License-Identifier: MIT

username: "nao"
usb_server: "http://198.18.0.1/apps"
app_prefix: "/home/nao/.local/share/PackageManager/apps"
